- name: demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo tasks on loops
      ansible.builtin.debugg:
        msg: fruit - {{ item }}
        loop:
          - mango
          - kiwi
          - banana
