- name: demo on loops
  hosts: localhost
  connection: local
  tasks:
    - name: Demo tasks on loops
      ansible.builtin.debug:
        msg: fruit name - {{ item }}
      loop:
          - mango
          - kiwi
          - banana
    - name: demo tasks for loop
      ansible.builtin.debug:
        msg: fruit name - {{ item.name}}  quantity - {{ item.quantity }}
      loop:
        - {name: mango, quantity:10}
        - {name: banana, quantity:20}
