- name: demo on facts
  hosts: localhost
  connection: local
  tasks:
    - name: print fact
      ansible.builtin.debug:
        msg: date - {{ ansible_date_time }}


#Arch - {{ ansible_architecture }}
